version: "3.8"
name: "ghost-link"
services:
  db:
    image: postgres
    container_name: db_data
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ghost_link_user
      POSTGRES_PASSWORD: ghost_link_password
      POSTGRES_DB: ghost_link_db
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
